#!/bin/sh

RECIPIENT="${1}"
TOKEN_FILE="${2}"
VERB="${3}"

case "${VERB}" in
  get)    gpg --decrypt < "${TOKEN_FILE}";;
  store)  gpg --encrypt -r "${RECIPIENT}" > "${TOKEN_FILE}";;
  forget) rm -f "${TOKEN_FILE}";;
esac
